Set Up Associations
DarkxDev/opp-school-library pull request #3
Opened 2023-04-12 23:12 UTC by DarkxDev

- Created `Classroom`, `Book`, and `Rental` classes.
- Created the `has-many`/`belongs-to` relationships.
- Created `many-to-many` relationship.

2023-04-12 23:39 UTC, codecaiine requested changes
Hi @DarkxDev  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Good class relationship setup :heavy_check_mark: 
- No rubocop errors :heavy_check_mark: 
- Good use of gitflow :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-12 23:39 UTC, codecaiine commented on classroom.rb
> +  end
- [ ] According to has-many / belongs-to relationships between Classroom and Student, getters and setters for the instance variable @Students should be present in Classroom class so that you can access that variable in Student class. Please fix it in order to make your app work as expected ✔️

2023-04-12 23:39 UTC, codecaiine commented on student.rb
> +    classroom.add_student(self)
- [ ] According to has-many / belongs-to relationships between Classroom and Student, when setting the classroom for a student it also adds it to the classrooms' students and that means a method that serves as the 'belongs-to' side (a student belongs to a classroom) should be present in Classroom class. Please take a look at the example below ⬇️  and fix it in order to make your app work as expected 👍 
```
def classroom=(classroom)
      @classroom = classroom
      classroom.students.push(self) unless classroom.students.include?(self)
  end
```

2023-04-12 23:39 UTC, codecaiine commented on book.rb
> +  end
- [ ] The book itself should be sent as a parameter to create the new rental achieving the 'has-many' association. Please check out the example below ⬇️  Please implement it in your code to make it completed 👍 
 ```
def add_rental(person, date)
    Rental.new(date, self, person)
 end

```

2023-04-12 23:39 UTC, codecaiine commented on rental.rb
> +#
- [ ] Removing commented code not only makes it harder to find later, but it also makes it so people in the future don't know it existed before. For finding the code, there are [tools and git commands](http://stackoverflow.com/q/278192/971592) to help you look at the history of a file. Please remove all commented code and unnecessary files from your code base :smile:

2023-04-12 23:39 UTC, codecaiine commented on person.rb
> +    @rentals = []
- [ ] the person itself should be sent as a parameter to create the new rental achieving the 'has-many' association. Kindly check out the example below ⬇️  Please implement it in your code to make it completed 👍
```
 def add_rental(book, date)
    Rental.new(date, book, self)
  end

```

2023-04-13 04:33 UTC, DarkxDev commented on classroom.rb
> +  end
Hi @codecaiine, thanks for the suggestion, but actually, the statement is not entirely correct. It is not necessary to have getters and setters for the instance variable @Students in the Classroom class to access that variable in the Student class.

Instead, we can set up the association between Classroom and Student using the attr_accessor method for the classroom attribute in the Student class. This way, we can access the Classroom object associated with a particular student using the "classroom" attribute in the Student class.

Here is how it's setup using the accessor mentioned in the project requirements:

![Untitled](https://user-images.githubusercontent.com/77408085/231633108-1ce5fde6-5dc7-4c8a-9778-96c66e17ff45.png)

You can test its functionality to get the desired result 👍

2023-04-13 04:33 UTC, DarkxDev commented on student.rb
> +    classroom.add_student(self)
Hi @codecaiine, thanks for the suggestion, however, the method you mention is the same one I'm using, when we call classroom.add_student. We reference the Classroom class method which executes `students << student` inside of it, which is actually an alias for `.push`, meaning it has the same effect as `classroom.students.push(self)`.

![asd](https://user-images.githubusercontent.com/77408085/231638411-806c1e9a-661e-4665-abb1-9fe25984fb10.png)

2023-04-13 04:33 UTC, DarkxDev commented on book.rb
> +  end
Great! Thanks for the suggestion @codecaiine, I've implemented the changes.

2023-04-13 04:33 UTC, DarkxDev commented on person.rb
> +    @rentals = []
Great! Thanks for the suggestion @codecaiine, I've implemented the changes.

2023-04-13 15:14 UTC, DarkxDev commented on rental.rb
> +#
Hi @codecaiine, thanks for the suggestion, I've removed the comments as requested, however, I would like to note that this is part of the documentation code reviewers can use to test the code, as I've been requested in previous projects.

You can test its functionality to get the desired result 👍 remember to use the corresponding `require` when using `IRB`

2023-04-13 16:29 UTC, medaminedev66 reviewed
Hello @DarkxDev 👋,

_This is an additional review as a result of the second opinion request._

I have reviewed your code and provided some clarifications of previous review. Please check the comments below the review 👇.

Keep rocking 🚀!

2023-04-13 17:02 UTC, DarkxDev commented on classroom.rb
> +  end
You're right! Thank you so much for the clarification 😄

2023-04-13 17:02 UTC, DarkxDev commented on student.rb
> +    classroom.add_student(self)
Consider it done!

2023-04-13 17:20 UTC, KDlamini approved these changes
### Hi @DarkxDev 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the required changes. 🎊 🥳 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!

## HIGHLIGHTS 🌟 

✔️ Good PR title and description
✔️ The `has-many` / `belongs-to` relationships between `Classroom` and `Student` are created
✔️ Relationship between `Person` and `Book` using the intermediate class `Rental` is well-implemented

# Status: Approved ✔️ 

![Great-job-smiley](https://user-images.githubusercontent.com/38088818/231835220-7b707d83-6181-4cd3-93bd-1afa268b536c.gif)

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-13 17:21 UTC, KDlamini commented on student.rb
> +    classroom.add_student(self)
Well resolved ✔️

2023-04-13 17:21 UTC, KDlamini commented on classroom.rb
> +  end
Well resolved ✔️

2023-04-13 17:24 UTC, merged